spring:
  profiles:
    active:
      - dev
---
server:
  port: 7001
spring:
  profiles: dev
  application:
    name: microservice-config-eureka-client-7001
eureka:
  instance:
    prefer-ip-address: true
    hostname: microservice-config-eureka-client7001
  client:
    service-url: defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: false # 当前的eureka-server自己不注册进服务列表中
    fetch-registry: false # 不通过eureka获取注册信息
---
server:
  port: 7001
spring:
  profiles: test
  application:
    name: microservice-config-eureka-client-7001

eureka:
  instance:
    prefer-ip-address: true
    hostname: microservice-config-eureka-client7001
  client:
    service-url: defaultZone: http://eureka7001.com:7001/eureka/
    register-with-eureka: false # 当前的eureka-server自己不注册进服务列表中
    fetch-registry: false # 不通过eureka获取注册信息