spring:
    profiles:
        active:
        - dev

---
server:
  port: 8201
spring:
  profiles: dev
  application:
    name: microservice-config-client-3355
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev.com:7001/eureka/
---
server:
  port: 8202
spring:
  profiles: test
  application:
    name: microservice-config-client-3355
eureka:
  client:
    service-url:
      defaultZone: http://eureka-test.com:7001/eureka/
