spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001
spring:
  profiles:
    active: dev
  application:
    name: microservice-provider-dept-8001
  datasource:
    url: jdbc:mysql://192.168.12.130:8889/microservice8001
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      dbcp2:
        min-idle: 5                                           # 数据库连接池的最小维持连接数
        initial-size: 5                                       # 初始化连接数
        max-total: 5                                          # 最大连接数
        max-wait-millis: 200
eureka:
  client:
    service-url: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: localhost
    prefer-ip-address: true

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.xue.springcloud.microserviceapi.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

info:
  app.name: xue-microservice
  company.name: www.xue.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8001
spring:
  profiles:
    active: test
  application:
    name: microservice-provider-dept-8001
  datasource:
    url: jdbc:mysql://192.168.12.130:8889/microservice8002
      username: root
      password: 123456
      driver-class-name: com.mysql.jdbc.Driver
      type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
      dbcp2:
        min-idle: 5                                           # 数据库连接池的最小维持连接数
        initial-size: 5                                       # 初始化连接数
        max-total: 5                                          # 最大连接数
        max-wait-millis: 200
eureka:
  client:
    service-url: http://eureka7001.com:7001/eureka/
  instance:
    instance-id: localhost
    prefer-ip-address: true

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml        # mybatis配置文件所在路径
  type-aliases-package: com.xue.springcloud.microserviceapi.entities    # 所有Entity别名类所在包
  mapper-locations:
    - classpath:mybatis/mapper/**/*.xml

info:
  app.name: xue-microservice
  company.name: www.xue.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$
