spring:
  profiles:
    active:
      - dev
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: microservicecloud-provider-dept-8001
---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: microservicecloud-provider-dept-8001
